Phase-1 Remove vavr dependency for CircuitBreaker and retry module
resilience4j/resilience4j pull request #1121
Opened 2020-08-16 17:48 UTC by KrnSaurabh

This Pull request is part of removing Vavr dependency from Resiliency4j- Phase 1.

This PR includes changes to make CircuitBreaker and Retry module entirely vavr independent. Changes are done to many other modules to back port the contract breaking changes done in core APIs.

My sincere apologies that the PR has become too long this time as I just couldn't keep track while back porting changes from core APIs.
I will try to keep the PRs smaller next time and iteratively remove Vavr from subsequent other modules.

@RobWin Let me know if the PR is too difficult to review. I will try to figure something out.

2020-08-19 05:36 UTC, RobWin commented
Thanks. I have a look at it.

2020-08-19 07:37 UTC, RobWin requested changes

2020-08-19 07:37 UTC, RobWin commented on resilience4j-spring/src/main/java/io/github/resilience4j/ratelimiter/configure/RateLimiterConfiguration.java
> +            rateLimiterConfigurationProperties.getTags());
I think we should create a defensive copy of the Map

2020-08-19 07:37 UTC, RobWin commented on resilience4j-spring/src/main/java/io/github/resilience4j/circuitbreaker/configure/CircuitBreakerConfiguration.java
> +        return CircuitBreakerRegistry.of(configs, circuitBreakerRegistryEventConsumer, circuitBreakerProperties.getTags());
I think we should create a defensive copy of the Map

2020-08-19 07:37 UTC, RobWin commented on resilience4j-spring/src/main/java/io/github/resilience4j/bulkhead/configure/threadpool/ThreadPoolBulkheadConfiguration.java
> +        return ThreadPoolBulkheadRegistry.of(configs, threadPoolBulkheadRegistryEventConsumer, threadPoolBulkheadConfigurationProperties.getTags());
I think we should create a defensive copy of the Map

2020-08-19 07:37 UTC, RobWin commented on resilience4j-spring/src/main/java/io/github/resilience4j/timelimiter/configure/TimeLimiterConfiguration.java
> +        return TimeLimiterRegistry.of(configs, timeLimiterRegistryEventConsumer, timeLimiterConfigurationProperties.getTags());
I think we should create a defensive copy of the Map

2020-08-19 07:37 UTC, RobWin commented on resilience4j-spring/src/main/java/io/github/resilience4j/retry/configure/RetryConfiguration.java
> +        return RetryRegistry.of(configs, retryRegistryEventConsumer, retryConfigurationProperties.getTags());
I think we should create a defensive copy of the Map

2020-08-19 07:38 UTC, RobWin commented
Thank you for your effort. Changes look very good!

2020-08-20 13:25 UTC, RobWin approved these changes

2020-08-20 13:26 UTC, merged

2020-08-20 14:08 UTC, KrnSaurabh commented
@RobWin  can you also sync 2.0 branch with current master. I tried creating a PR to merge recent changes to 2.0 from master but I am getting some error and unable to create the Pull request.