Implemented Context Aware scheduled thread pool for bulkhead
resilience4j/resilience4j pull request #1204
Opened 2020-10-14 11:44 UTC by KrnSaurabh

As per our internal discussion, replaced `ThreadPoolExecutor` by `ContextAwareBoundedScheduledThreadPool` inside `ThreadPoolBulkhead`.
`ContextAwareBoundedScheduledThreadPool` extends to `ScheduledThreadPoolExecutor` but maintains a boundedBlocking queue implementation using semaphore to control number of task submitted to queue.
it respects list of `ContextPropagators` configured in `ThreadPoolBulkhead` and propagates the same. Also it propagates `MDC` contextMap by default if set in caller thread.

Kindly review implementation of `ContextAwareBoundedScheduledThreadPool`. would it be better to implement `ScheduledThreadPoolExecutor` by ThreadPoolBulkhead itself or a separate implementation like this is fine ?
Also how are we planning to use the same threadpool in timeLimiter and retry? I guess we might need additional config to pass bulkhead instance to timeLimiter ?
@RobWin .

2020-11-02 07:05 UTC, KrnSaurabh commented
@RobWin  As we discussed earlier, I have:
* added spring config for injecting ContextAwareScheduledThreadPool
* We can initialise ContextAwareScheduledThreadPool and pass it as parameter to timelimiter when using Decorators.
Kindly Review and let me know your initial feedback.

WIP:
* Need implement same in Retry as we did in TimeLimiter.
* Need to add many test cases.

2020-11-02 10:34 UTC, RobWin requested changes

2020-11-02 10:34 UTC, RobWin commented on resilience4j-core/src/main/java/io/github/resilience4j/core/ContextAwareScheduledThreadPool.java
> +public class ContextAwareScheduledThreadPool extends ScheduledThreadPoolExecutor {
Can we rename it to  
`ContextAwareScheduledThreadPoolExecutor `?

2020-11-13 14:10 UTC, KrnSaurabh commented
@RobWin I have added `ContextAwareThreadPoolExecutor` to RetryAsync. Kindly review below test cases for the same. 

https://github.com/resilience4j/resilience4j/pull/1204/files#diff-f721c28553ba6de437c67a84c0ce99209adee9d478b82c399f9966a762674aa2R584

https://github.com/resilience4j/resilience4j/pull/1204/files#diff-b3255db60bc55ad54dd4d6fcd2fb8cff7992287d182ec11e2015856191a343e2R122

2020-11-17 08:34 UTC, RobWin commented
TimeLimiter is done as well, or?

2020-11-17 08:40 UTC, KrnSaurabh commented
> TimeLimiter is done as well, or?

2020-11-17 08:41 UTC, KrnSaurabh commented
yes Timelimiter is also done. I might have to look and see if I need to add more test cases.

2020-11-18 07:30 UTC, RobWin commented
Yes, the solution looks good to me 👍

2020-11-25 11:55 UTC, KrnSaurabh commented
@RobWin I have completed this PR from my side. Kindly do a final review.

2020-11-30 08:43 UTC, RobWin approved these changes

2020-11-30 08:46 UTC, merged